version: '3.8'

services:
  traefik-config:
    image: ghcr.io/hannes-sistemica/traefik-dynamic:latest
    container_name: traefik-config-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
