services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    platform: linux/amd64
    ports:
      - "8081:8080"  # Dashboard
      - "9080:80"    # HTTP
      - "9443:443"   # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.http.endpoint=http://traefik-config:5001/config
      - --providers.http.pollInterval=10s
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

  traefik-config:
    image: ghcr.io/hannes-sistemica/traefik-dynamic:latest
    container_name: traefik-config-server
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=secret

