{
  "http": {
    "services": {
      "gitea": {
        "loadBalancer": {
          "servers": [
            {
              "url": "http://192.168.1.2:3000"
            }
          ]
        }
      }
    },
    "routers": {
      "gitea-router": {
        "rule": "Host(`gitea.zuhauhomese`)",
        "service": "gitea",
        "entryPoints": ["websecure"],
        "tls": true
      }
    }
  }
}